<br>
<h1 style = "font-size:40px; font-family:cursive ; font-weight : normal; color : #C70039; text-align: center; border-radius: 10px 100px;">IPL Data Analysis and Visualization Project using Python</h1>
<br>



In this project, I have worked on IPL Data Analysis and Visualization using Python where I will explore interesting insights from the data of IPL matches with data from IPL seasons 2008–2020.

## **Analysis covered in this project** :

1. <a href='#1'> What was the count of matches played in each season?</a>
 
2. <a href='#2'>How many runs were scored in each season?</a>
 
3. <a href='#3'>What were the runs scored per match in different seasons? </a>
 
4. <a href='#4'>Who has umpired the most?</a>
 
5. <a href='#5'>Which team has won the most tosses?</a>
 
6. <a href='#6'>What does the team decide after winning the toss?</a>
 
7. <a href='#7'>How toss decision varies across seasons?</a>
 
8. <a href='#8'>Does winning the toss implies winning the game?</a>
 
9. <a href='#9'>How many times chasing team has won the match?</a>
 
10. <a href='#10'>Which all teams had won this tournament?</a>
 
11. <a href='#11'>Which team has played the most number of matches?</a>
 
12. <a href='#12'>Which team has won the most number of times?</a>
 
13. <a href='#13'>Which team has the highest winning percentage?</a>
 
14. <a href='#14'>Is there any lucky venue for a particular team?</a>
 
15. <a href='#15'>Comparison between two teams</a>
 
16. <a href='#16'>Particular Batsmen analysis</a>
 
17. <a href='#17'>Innings wise comparison between teams</a>
 
18. <a href='#18'>Which team has scored the most number of 200+ scores?</a>
 
19. <a href='#19'>Which team has conceded 200+ scores the most?</a>
 
20. <a href='#20'>What was the highest run scored by a team in a single match?</a>
 
21. <a href='#21'>Which is the biggest win in terms of run margin?</a>
 
22. <a href='#22'>Which batsmen have played the most number of balls?</a>
 
23. <a href='#23'>Who are the leading run-scorers of all time?</a>
 
24. <a href='#24'>Who has hit the most number of 4's?</a>
 
25. <a href='#25'>Who has hit the most number of 6's?</a>
 
26. <a href='#26'>Who has the highest strike rate?</a>
 
27. <a href='#27'>Who is the leading wicket-taker?</a>
 
28. <a href='#28'>Which stadium has hosted the most number of matches?</a>
 
29. <a href='#29'>Who has won the most MOM awards?</a>
 
30. <a href='#30'>What is the count of fours hit in each season?</a>
 
31. <a href='#31'>What is the count of sixes hit in each season?</a>
 
32. <a href='#32'>What is the count of runs scored from boundaries in each season?</a>
 
33. <a href='#33'>What is the run contribution from boundaries in each season?</a>
 
34. <a href='#34'>Which team has scored the most runs in the first 6 overs?</a>
 
35. <a href='#35'>Which team has scored the most runs in the last 4 overs?</a>
 
36. <a href='#36'>Which team has the best scoring run-rate in the first 6 overs?</a>
 
37. <a href='#37'>Which team has the best scoring run-rate in the last 4 overs?</a>

38. <a href='#38'>Who are the top 10 fielders?</a>

39. <a href='#39'>Which are the smallest wins in terms of run margin?</a>

40. <a href='#40'>What are the top most dismissmal reasons</a>

In [6]:
import numpy as np
import pandas as pd

import os


<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">Importing libraries:</h1>

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
import plotly.express as px
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, plot, iplot
from plotly import tools
from warnings import filterwarnings
filterwarnings('ignore')

<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;"> Loading match and deliveries dataset:</h1>

In [8]:
deliveries_data = pd.read_csv('/content/IPL Ball-by-Ball 2008-2020.csv')
match_data = pd.read_csv('/content/IPL Matches 2008-2020.csv')
print("Data ready for exploration")

Data ready for exploration


<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;"> Basic data exploration:</h1>


In [9]:
match_data.head()

id        city        date player_of_match  \
0  335982   Bangalore  2008-04-18     BB McCullum   
1  335983  Chandigarh  2008-04-19      MEK Hussey   
2  335984       Delhi  2008-04-19     MF Maharoof   
3  335985      Mumbai  2008-04-20      MV Boucher   
4  335986     Kolkata  2008-04-20       DJ Hussey   

                                        venue  neutral_venue  \
0                       M Chinnaswamy Stadium              0   
1  Punjab Cricket Association Stadium, Mohali              0   
2                            Feroz Shah Kotla              0   
3                            Wankhede Stadium              0   
4                                Eden Gardens              0   

                         team1                        team2  \
0  Royal Challengers Bangalore        Kolkata Knight Riders   
1              Kings XI Punjab          Chennai Super Kings   
2             Delhi Daredevils             Rajasthan Royals   
3               Mumbai Indians  Royal Challengers Bangalore   
4        Kolkata Knight Riders              Deccan Chargers   

                   toss_winner toss_decision                       winner  \
0  Royal Challengers Bangalore         field        Kolkata Knight Riders   
1          Chennai Super Kings           bat          Chennai Super Kings   
2             Rajasthan Royals           bat             Delhi Daredevils   
3               Mumbai Indians           bat  Royal Challengers Bangalore   
4              Deccan Chargers           bat        Kolkata Knight Riders   

    result  result_margin eliminator method    umpire1         umpire2  
0     runs          140.0          N    NaN  Asad Rauf     RE Koertzen  
1     runs           33.0          N    NaN  MR Benson      SL Shastri  
2  wickets            9.0          N    NaN  Aleem Dar  GA Pratapkumar  
3  wickets            5.0          N    NaN   SJ Davis       DJ Harper  
4  wickets            5.0          N    NaN  BF Bowden     K Hariharan

In [10]:
deliveries_data.head()

id  inning  over  ball      batsman  non_striker     bowler  \
0  335982       1     6     5   RT Ponting  BB McCullum  AA Noffke   
1  335982       1     6     6  BB McCullum   RT Ponting  AA Noffke   
2  335982       1     7     1  BB McCullum   RT Ponting     Z Khan   
3  335982       1     7     2  BB McCullum   RT Ponting     Z Khan   
4  335982       1     7     3   RT Ponting  BB McCullum     Z Khan   

   batsman_runs  extra_runs  total_runs  non_boundary  is_wicket  \
0             1           0           1             0          0   
1             1           0           1             0          0   
2             0           0           0             0          0   
3             1           0           1             0          0   
4             1           0           1             0          0   

  dismissal_kind player_dismissed fielder extras_type           batting_team  \
0            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
1            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
2            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
3            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
4            NaN              NaN     NaN         NaN  Kolkata Knight Riders   

                  bowling_team  
0  Royal Challengers Bangalore  
1  Royal Challengers Bangalore  
2  Royal Challengers Bangalore  
3  Royal Challengers Bangalore  
4  Royal Challengers Bangalore

In [11]:
match_data.isnull().sum()

id                   0
city                13
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
dtype: int64

In [12]:
match_data.shape

(816, 17)

In [13]:
match_data.columns

Index(['id', 'city', 'date', 'player_of_match', 'venue', 'neutral_venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'eliminator', 'method', 'umpire1', 'umpire2'],
      dtype='object')

In [14]:
print('Total Matches Played:',match_data.shape[0])
print(' \n Venues Played At:',match_data['city'].unique())     
print(' \n Teams :',match_data['team1'].unique())

Total Matches Played: 816
 
 Venues Played At: ['Bangalore' 'Chandigarh' 'Delhi' 'Mumbai' 'Kolkata' 'Jaipur' 'Hyderabad'
 'Chennai' 'Cape Town' 'Port Elizabeth' 'Durban' 'Centurion' 'East London'
 'Johannesburg' 'Kimberley' 'Bloemfontein' 'Ahmedabad' 'Cuttack' 'Nagpur'
 'Dharamsala' 'Kochi' 'Indore' 'Visakhapatnam' 'Pune' 'Raipur' 'Ranchi'
 'Abu Dhabi' nan 'Rajkot' 'Kanpur' 'Bengaluru' 'Dubai' 'Sharjah']
 
 Teams : ['Royal Challengers Bangalore' 'Kings XI Punjab' 'Delhi Daredevils'
 'Mumbai Indians' 'Kolkata Knight Riders' 'Rajasthan Royals'
 'Deccan Chargers' 'Chennai Super Kings' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Gujarat Lions'
 'Rising Pune Supergiants' 'Rising Pune Supergiant' 'Delhi Capitals']


<a id="1">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;"> 1) Number of matches played in various seasons :</h1>


In [15]:
match_data['Season'] = pd.DatetimeIndex(match_data['date']).year
match_data.head()

id        city        date player_of_match  \
0  335982   Bangalore  2008-04-18     BB McCullum   
1  335983  Chandigarh  2008-04-19      MEK Hussey   
2  335984       Delhi  2008-04-19     MF Maharoof   
3  335985      Mumbai  2008-04-20      MV Boucher   
4  335986     Kolkata  2008-04-20       DJ Hussey   

                                        venue  neutral_venue  \
0                       M Chinnaswamy Stadium              0   
1  Punjab Cricket Association Stadium, Mohali              0   
2                            Feroz Shah Kotla              0   
3                            Wankhede Stadium              0   
4                                Eden Gardens              0   

                         team1                        team2  \
0  Royal Challengers Bangalore        Kolkata Knight Riders   
1              Kings XI Punjab          Chennai Super Kings   
2             Delhi Daredevils             Rajasthan Royals   
3               Mumbai Indians  Royal Challengers Bangalore   
4        Kolkata Knight Riders              Deccan Chargers   

                   toss_winner toss_decision                       winner  \
0  Royal Challengers Bangalore         field        Kolkata Knight Riders   
1          Chennai Super Kings           bat          Chennai Super Kings   
2             Rajasthan Royals           bat             Delhi Daredevils   
3               Mumbai Indians           bat  Royal Challengers Bangalore   
4              Deccan Chargers           bat        Kolkata Knight Riders   

    result  result_margin eliminator method    umpire1         umpire2  Season  
0     runs          140.0          N    NaN  Asad Rauf     RE Koertzen    2008  
1     runs           33.0          N    NaN  MR Benson      SL Shastri    2008  
2  wickets            9.0          N    NaN  Aleem Dar  GA Pratapkumar    2008  
3  wickets            5.0          N    NaN   SJ Davis       DJ Harper    2008  
4  wickets            5.0          N    NaN  BF Bowden     K Hariharan    2008

In [16]:
match_per_season=match_data.groupby(['Season'])['id'].count().reset_index().rename(columns={'id':'matches'})
match_per_season.style.background_gradient(cmap='PuBu')

In [17]:
colors = ['turquoise',] * 13
colors[5] = 'crimson'

fig=px.bar(data_frame=match_per_season,x=match_per_season.Season,y=match_per_season.matches,labels=dict(x="Season",y="Count"),)
fig.update_layout(title="Number of matches played in different seasons ",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()

<div class="alert alert-block alert-info"><p style='color:black;'> 📌Each season, almost 60 matches were played. However, we see a spike in the number of matches from 2011 to 2013. This is because two new franchises, the Pune Warriors and Kochi Tuskers Kerala, were introduced, increasing the number of teams to 10.</p>
</div>

<a id="2">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;"> 2) Total number of runs scored across seasons :</h1>


In [18]:
season_data=match_data[['id','Season']].merge(deliveries_data, left_on = 'id', right_on = 'id', how = 'left').drop('id', axis = 1)
season_data.head()

Season  inning  over  ball      batsman  non_striker     bowler  \
0    2008       1     6     5   RT Ponting  BB McCullum  AA Noffke   
1    2008       1     6     6  BB McCullum   RT Ponting  AA Noffke   
2    2008       1     7     1  BB McCullum   RT Ponting     Z Khan   
3    2008       1     7     2  BB McCullum   RT Ponting     Z Khan   
4    2008       1     7     3   RT Ponting  BB McCullum     Z Khan   

   batsman_runs  extra_runs  total_runs  non_boundary  is_wicket  \
0             1           0           1             0          0   
1             1           0           1             0          0   
2             0           0           0             0          0   
3             1           0           1             0          0   
4             1           0           1             0          0   

  dismissal_kind player_dismissed fielder extras_type           batting_team  \
0            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
1            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
2            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
3            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
4            NaN              NaN     NaN         NaN  Kolkata Knight Riders   

                  bowling_team  
0  Royal Challengers Bangalore  
1  Royal Challengers Bangalore  
2  Royal Challengers Bangalore  
3  Royal Challengers Bangalore  
4  Royal Challengers Bangalore

In [19]:
season=season_data.groupby(['Season'])['total_runs'].sum().reset_index()
p=season.set_index('Season')
fig = px.line(p, x=p.index, y="total_runs")
fig.update_layout(title="Total Runs Across the Seasons ",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.show()

</div>
<div class="alert alert-block alert-info"><p style='color:black;'> 📌<b>Season 2013</b> was the highest scoring season (22,541 runs), followed by 2012 (22,453 runs)<br>
<b>Season 2009</b> was the lowest scoring season (16,320 runs).</p>
</div>

<a id="3">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;"> 3) Runs scored per match across seasons :</h1>


In [20]:
runs_per_season=pd.concat([match_per_season,season.iloc[:,1]],axis=1)
runs_per_season['Runs scored per match']=runs_per_season['total_runs']/runs_per_season['matches']
runs_per_season.set_index('Season',inplace=True)
runs_per_season.style.background_gradient(cmap='PuBu',subset=['Runs scored per match'])

In [21]:
fig = px.line(runs_per_season, x=runs_per_season.index, y="Runs scored per match")
fig.update_layout(title="Runs scored per match across seasons",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌In <b>season 2018</b>, runs scored per match was 331.683333 which was highest among others.<br> 
In <b>season 2009</b>, runs scored per match was 286.315789 which was lowest till now.</p> </div>

<a id="4">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black"> 4) Count of matches by umpires :</h1>



In [22]:
ump=pd.concat([match_data['umpire1'],match_data['umpire2']])
ump=ump.value_counts()
umps=ump.to_frame().reset_index()
ump.head(10)

S Ravi             121
HDPK Dharmasena     94
AK Chaudhary        87
C Shamshuddin       82
M Erasmus           65
CK Nandan           57
Nitin Menon         57
SJA Taufel          55
Asad Rauf           51
VA Kulkarni         50
dtype: int64

<div class="alert alert-block alert-info"><p style='color:black;'> 📌<b>S Ravi</b> has umpired in 121 matches, followed by Dharmasena who has umpired in 94 matches.
</p>
</div>

<a id="5">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;"> 5) Number of tosses won by teams :</h1>




In [23]:
match_data['toss_winner'].value_counts()

Mumbai Indians                 106
Kolkata Knight Riders           98
Chennai Super Kings             97
Royal Challengers Bangalore     87
Rajasthan Royals                87
Kings XI Punjab                 85
Delhi Daredevils                80
Sunrisers Hyderabad             57
Deccan Chargers                 43
Pune Warriors                   20
Delhi Capitals                  20
Gujarat Lions                   15
Kochi Tuskers Kerala             8
Rising Pune Supergiants          7
Rising Pune Supergiant           6
Name: toss_winner, dtype: int64

In [24]:
toss=match_data['toss_winner'].value_counts()
colors = ['turquoise',] * 15
colors[0] = 'crimson'
fig=px.bar( y=toss,x=toss.index,labels=dict(x="Season",y="Count"),)
fig.update_layout(title="No. of tosses won by each team",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()

<div class="alert alert-block alert-info"><p style='color:black;'> 📌<b>Mumbai Indians</b> have won the most tosses, followed by Kolkata Knight Riders.
</p>
</div>

<a id="6">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;"> 6) Decision made after winning the toss :</h1>

In [25]:
temp_series = match_data.toss_decision.value_counts()
labels = (np.array(temp_series.index))
values = (np.array((temp_series / temp_series.sum())*100))
colors = ['turquoise', 'crimson']
fig = go.Figure(data=[go.Pie(labels=labels,
                             values=values,hole=.3)])
fig.update_traces(hoverinfo='label+percent', textinfo='label+percent', textfont_size=20,
                  marker=dict(colors=colors, line=dict(color='#000000', width=3)))
fig.update_layout(title="Toss decision percentage",
                  titlefont={'size': 30},
                  )
fig.show()

<div class="alert alert-block alert-info"><p style='color:black;'> 📌After winning the toss, team tends to field first<br>
</p>
</div>

<a id="7">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;"> 7) Toss decision across seasons :</h1>



In [26]:
fig=px.histogram(data_frame=match_data,x='Season',color='toss_decision',color_discrete_sequence=colors,barmode='group')
fig.update_layout(title="Toss decision in different seasons",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1)
fig.show()

<div class="alert alert-block alert-info"><p style='color:black;'> 📌Most of the times, teams decide to feild first except in season 2009,2010,2013 where teams decided to bat first mostly.<br>
Since 2014, teams have overwhelmingly chosen to bat second. Especially since 2016, teams have chosen to field for more than 80% of the times except in season 2020.<br>
</p>
</div>

<a id="8">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;"> 8)Winning toss implies winning game ?</h1>


In [27]:
match_data['toss_win_game_win'] = np.where((match_data.toss_winner == match_data.winner),'Yes','No')
match_data.head()

id        city        date player_of_match  \
0  335982   Bangalore  2008-04-18     BB McCullum   
1  335983  Chandigarh  2008-04-19      MEK Hussey   
2  335984       Delhi  2008-04-19     MF Maharoof   
3  335985      Mumbai  2008-04-20      MV Boucher   
4  335986     Kolkata  2008-04-20       DJ Hussey   

                                        venue  neutral_venue  \
0                       M Chinnaswamy Stadium              0   
1  Punjab Cricket Association Stadium, Mohali              0   
2                            Feroz Shah Kotla              0   
3                            Wankhede Stadium              0   
4                                Eden Gardens              0   

                         team1                        team2  \
0  Royal Challengers Bangalore        Kolkata Knight Riders   
1              Kings XI Punjab          Chennai Super Kings   
2             Delhi Daredevils             Rajasthan Royals   
3               Mumbai Indians  Royal Challengers Bangalore   
4        Kolkata Knight Riders              Deccan Chargers   

                   toss_winner toss_decision                       winner  \
0  Royal Challengers Bangalore         field        Kolkata Knight Riders   
1          Chennai Super Kings           bat          Chennai Super Kings   
2             Rajasthan Royals           bat             Delhi Daredevils   
3               Mumbai Indians           bat  Royal Challengers Bangalore   
4              Deccan Chargers           bat        Kolkata Knight Riders   

    result  result_margin eliminator method    umpire1         umpire2  \
0     runs          140.0          N    NaN  Asad Rauf     RE Koertzen   
1     runs           33.0          N    NaN  MR Benson      SL Shastri   
2  wickets            9.0          N    NaN  Aleem Dar  GA Pratapkumar   
3  wickets            5.0          N    NaN   SJ Davis       DJ Harper   
4  wickets            5.0          N    NaN  BF Bowden     K Hariharan   

   Season toss_win_game_win  
0    2008                No  
1    2008               Yes  
2    2008                No  
3    2008                No  
4    2008                No

In [28]:
labels =["Yes",'No']
values = match_data['toss_win_game_win'].value_counts()
colors = ['turquoise', 'crimson']
fig = go.Figure(data=[go.Pie(labels=labels,
                             values=values,hole=.3)])
fig.update_traces(hoverinfo='label+percent', textinfo='label+percent', textfont_size=20,
                  marker=dict(colors=colors, line=dict(color='#000000', width=3)))
fig.update_layout(title="Winning toss implies winning macthes?",
                  titlefont={'size': 30},
                  )
fig.show()

<div class="alert alert-block alert-info"><p style='color:black;'> 📌Though winning toss gives you an advantage <b>but it doesn't significantly implies that winning the toss helps in winning the game.</b>
</p>
</div>

<a id="9">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;"> 9) Match win result:</h1>


In [29]:
match_data['result'].value_counts()

wickets    435
runs       364
tie         13
Name: result, dtype: int64

<div class="alert alert-block alert-info"><p style='color:black;'> 📌We can see that <b>435 out of 816 matches was won by team batting second</b> while 364 matches was won by team batting first.
</p>
</div>



<a id="10">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;"> 10) Number of times team have won the tournament :</h1>

In [30]:
winning_teams = match_data[['Season','winner']]

#dictionaries to get winners to each season
winners_team = {}
for i in sorted(winning_teams.Season.unique()):
    winners_team[i] = winning_teams[winning_teams.Season == i]['winner'].tail(1).values[0]
    
winners_of_IPL = pd.Series(winners_team)
winners_of_IPL = pd.DataFrame(winners_of_IPL, columns=['team'])

In [31]:
winners_of_IPL.value_counts().index

MultiIndex([(       'Mumbai Indians',),
            (  'Chennai Super Kings',),
            ('Kolkata Knight Riders',),
            (      'Deccan Chargers',),
            (     'Rajasthan Royals',),
            (  'Sunrisers Hyderabad',)],
           names=['team'])

In [32]:
colors = ['turquoise',] * 6
colors[0] = 'crimson'
fig=px.bar( y=winners_of_IPL['team'].value_counts(),x=winners_of_IPL['team'].value_counts().index,labels=dict(x="Team Name",y="Count"),)
fig.update_layout(title="Winners of IPL",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
<b>Mumbai Indians had won the IPL 5 times</b> while Chennai Super Kings had won it 3 times.
</p>
</div>

<a id="11">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;"> 11) Total number of matches played by a team :</h1>


In [33]:
matches_played_byteams=pd.concat([match_data['team1'],match_data['team2']],axis=1)
teams=(matches_played_byteams['team1'].value_counts()+matches_played_byteams['team2'].value_counts()).reset_index()
teams.columns=['Team Name','Total Matches played']
teams.sort_values(by=['Total Matches played'],ascending=False).reset_index().drop('index',axis=1).style.background_gradient(cmap='PuBu')

In [34]:
wins=pd.DataFrame(match_data['winner'].value_counts()).reset_index()
wins.columns=['Team Name','Wins']
wins.style.background_gradient(cmap='PuBu')

In [35]:
played=teams.merge(wins,left_on='Team Name',right_on='Team Name',how='inner')
played['% Win']=(played['Wins']/played['Total Matches played'])*100
played.sort_values(by=['% Win'],ascending=False).reset_index().drop('index',axis=1).style.background_gradient(cmap='PuBu',subset=['% Win'])

In [36]:
colors = ['turquoise',] * 15
colors[8] = 'crimson'
fig=px.bar(x=played['Team Name'],y=played['Total Matches played'],labels=dict(x="Team Name",y="Count"),)
fig.update_layout(title="Total number of matches played",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Mumbai Indians have played the most matches(203), followed by Royal Challengers Bangalore (195)
</p>
</div>

<a id="12">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;"> 12) Most number of wins :</h1>

In [37]:
colors = ['turquoise',] * 15
colors[8] = 'crimson'
fig=px.bar(x=played['Team Name'],y=played['Wins'],labels=dict(x="Team Name",y="Count"),)
fig.update_layout(title="Total Win by teams",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Mumbai Indians had won the most matches(120), followed by Chennai Super Kings (106)
</p>
</div>


<a id="13">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;"> 13) Win % by teams :</h1>


In [38]:
colors = ['turquoise',] * 15
colors[-4] = 'crimson'
fig=px.bar(x=played['Team Name'],y=played['% Win'],labels=dict(x="Team Name",y="Count"),)
fig.update_layout(title="Win % by teams",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Rising Pune Supergiants have the highest win % of 62.50, followed by Chennai Super kings and Mumbai Indians.<br> 
This is largely due to the fact that they had played really few matches.
</p>
</div>


<a id="14">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">14) Lucky Venues for a team :</h1>

In [39]:
def lucky(match_data,team_name):
    return match_data[match_data['winner']==team_name]['venue'].value_counts().nlargest(10)

In [40]:
mi=lucky(match_data,'Mumbai Indians')
values = mi
labels=mi.index
colors = ['turquoise', 'crimson']
fig = go.Figure(data=[go.Pie(labels=labels,values=values,hole=.3)])
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=20,
                  marker=dict(colors=colors, line=dict(color='#000000', width=3)))
fig.update_layout(title="Wins at different Venues for MI:",
                  titlefont={'size': 30},
                  )
fig.show()

In [41]:
rcb=lucky(match_data,'Royal Challengers Bangalore')
values = rcb
labels=rcb.index
colors = ['turquoise', 'crimson']
fig = go.Figure(data=[go.Pie(labels=labels,values=values,hole=.3)])
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=20,
                  marker=dict(colors=colors, line=dict(color='#000000', width=3)))
fig.update_layout(title="Wins at different Venues for RCB:",
                  titlefont={'size': 30},
                  )
fig.show()

In [42]:
csk=lucky(match_data,'Chennai Super Kings')
values = csk
labels=csk.index
colors = ['turquoise', 'crimson']
fig = go.Figure(data=[go.Pie(labels=labels,values=values,hole=.3)])
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=20,
                  marker=dict(colors=colors, line=dict(color='#000000', width=3)))
fig.update_layout(title="Wins at different Venues for CSK:",
                  titlefont={'size': 30},
                  )
fig.show()

In [43]:
csk=lucky(match_data,'Kolkata Knight Riders')
values = csk
labels=csk.index
colors = ['turquoise', 'crimson']
fig = go.Figure(data=[go.Pie(labels=labels,values=values,hole=.3)])
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=20,
                  marker=dict(colors=colors, line=dict(color='#000000', width=3)))
fig.update_layout(title="Wins at different Venues for KKR:",
                  titlefont={'size': 30},
                  )
fig.show()

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
It is easily evident that team have won the most of its matches at their home venues.
</p>
</div>



<a id="15">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">15) Comparision between two teams :</h1>



In [44]:
def comparison(team1,team2):
    compare=match_data[((match_data['team1']==team1)|(match_data['team2']==team1))&((match_data['team1']==team2)|(match_data['team2']==team2))]
    fig=px.histogram(data_frame=compare,x='Season',color='winner',labels=dict(x="Team Name",y="Count"),barmode='group',nbins=16,color_discrete_sequence=colors,)
    fig.update_layout(title="Team Comparision:",
                      titlefont={'size': 26},template='simple_white'     
                      )
    fig.update_traces(marker_line_color='black',
                      marker_line_width=2.5, opacity=1)
    fig.show()
    

In [45]:
comparison('Mumbai Indians','Chennai Super Kings')

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Mumbai Indians is slight ahead of Chennai Super Kings in this heavy clash.<br>
The dominance was especially seen in the 2019 season, where Mumbai defeated Chennai 4 out of 4 times they met, including the playoff and final.
</p>
</div>

In [46]:
comparison('Sunrisers Hyderabad','Royal Challengers Bangalore')

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
We can observe that this one is a very tight clash, with most of the times both the teams winning one each.<br>
   Sunrisers Hyderabad had an upper hand in 2016 and 2020
</p>
</div>

<a id="16">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">16) Particular batsman analysis :</h1>



<div class="alert alert-block alert-info"><p style='color:black;'> 📌
    Lets see some stats of highest run scorer of IPL : <b>Virat Kohli</b>
</p>
</div>

In [47]:
filt=(deliveries_data['batsman']=='V Kohli')
df_kohli=deliveries_data[filt]
df_kohli.head()

id  inning  over  ball  batsman non_striker    bowler  batsman_runs  \
211  335982       2     1     2  V Kohli    W Jaffer  I Sharma             0   
212  335982       2     1     3  V Kohli    W Jaffer  I Sharma             0   
213  335982       2     1     4  V Kohli    W Jaffer  I Sharma             1   
216  335982       2     2     1  V Kohli    W Jaffer  AB Dinda             0   
217  335982       2     2     2  V Kohli    W Jaffer  AB Dinda             0   

     extra_runs  total_runs  non_boundary  is_wicket dismissal_kind  \
211           0           0             0          0            NaN   
212           4           4             0          0            NaN   
213           0           1             0          0            NaN   
216           0           0             0          0            NaN   
217           0           0             0          1         bowled   

    player_dismissed fielder extras_type                 batting_team  \
211              NaN     NaN         NaN  Royal Challengers Bangalore   
212              NaN     NaN     legbyes  Royal Challengers Bangalore   
213              NaN     NaN         NaN  Royal Challengers Bangalore   
216              NaN     NaN         NaN  Royal Challengers Bangalore   
217          V Kohli     NaN         NaN  Royal Challengers Bangalore   

              bowling_team  
211  Kolkata Knight Riders  
212  Kolkata Knight Riders  
213  Kolkata Knight Riders  
216  Kolkata Knight Riders  
217  Kolkata Knight Riders

In [48]:
values = df_kohli['dismissal_kind'].value_counts()
labels=df_kohli['dismissal_kind'].value_counts().index
fig = go.Figure(data=[go.Pie(labels=labels,values=values,hole=.3)])
fig.update_traces(hoverinfo='label+percent', textinfo='label', textfont_size=20,
                  marker=dict(colors=colors, line=dict(color='#000000', width=3)))
fig.update_layout(title="Dismissal Type",
                  titlefont={'size': 30},
                  )
fig.show()

In [49]:
len(df_kohli[df_kohli['batsman_runs']==4])

504

In [50]:
len(df_kohli[df_kohli['batsman_runs']==6])

202

In [51]:
df_kohli['total_runs'].sum()

6081

In [52]:
def count(df_kohli,runs):
    return len(df_kohli[df_kohli['batsman_runs']==runs])*runs

In [53]:
print("Runs scored from 1's :",count(df_kohli,1))
print("Runs scored from 2's :",count(df_kohli,2))
print("Runs scored from 3's :",count(df_kohli,3))
print("Runs scored from 4's :",count(df_kohli,4))
print("Runs scored from 6's :",count(df_kohli,6))

Runs scored from 1's : 1919
Runs scored from 2's : 692
Runs scored from 3's : 39
Runs scored from 4's : 2016
Runs scored from 6's : 1212


In [54]:
values=[count(df_kohli,1),count(df_kohli,2),count(df_kohli,3),count(df_kohli,4),count(df_kohli,6)]
labels=[1,2,3,4,6]
fig = go.Figure(data=[go.Pie(labels=labels,values=values,hole=.3)])
fig.update_traces(hoverinfo='label+percent', textinfo='label+value', textfont_size=20,
                  marker=dict(colors=colors, line=dict(color='#000000', width=3)))
fig.update_layout(title="Virat Kohli total runs contribution",
                  titlefont={'size': 30},
                  )
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
    Interesting fact is that <b>Virat Kohli</b> has scored more runs by taking singles than by hitting 6
</p>
</div>

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
    Lets see some stats of another versatile player : <b>David Warner</b>
</p>
</div>

In [55]:
filt=(deliveries_data['batsman']=='DA Warner')
df_warner=deliveries_data[filt]
df_warner.head()

id  inning  over  ball    batsman non_striker     bowler  \
18954  392206       2     3     5  DA Warner  TM Dilshan    S Tyagi   
18956  392206       2     4     1  DA Warner  TM Dilshan  JA Morkel   
18957  392206       2     4     2  DA Warner  TM Dilshan  JA Morkel   
18958  392206       2     4     3  DA Warner  TM Dilshan  JA Morkel   
18959  392206       2     4     4  DA Warner  TM Dilshan  JA Morkel   

       batsman_runs  extra_runs  total_runs  non_boundary  is_wicket  \
18954             0           1           1             0          0   
18956             0           0           0             0          0   
18957             4           0           4             0          0   
18958             4           0           4             0          0   
18959             4           0           4             0          0   

      dismissal_kind player_dismissed fielder extras_type      batting_team  \
18954            NaN              NaN     NaN     legbyes  Delhi Daredevils   
18956            NaN              NaN     NaN         NaN  Delhi Daredevils   
18957            NaN              NaN     NaN         NaN  Delhi Daredevils   
18958            NaN              NaN     NaN         NaN  Delhi Daredevils   
18959            NaN              NaN     NaN         NaN  Delhi Daredevils   

              bowling_team  
18954  Chennai Super Kings  
18956  Chennai Super Kings  
18957  Chennai Super Kings  
18958  Chennai Super Kings  
18959  Chennai Super Kings

In [56]:
values = df_warner['dismissal_kind'].value_counts()
labels=df_warner['dismissal_kind'].value_counts().index
fig = go.Figure(data=[go.Pie(labels=labels,values=values,hole=.3)])
fig.update_traces(hoverinfo='label+percent', textinfo='label', textfont_size=20,
                  marker=dict(colors=colors, line=dict(color='#000000', width=3)))
fig.update_layout(title="Dismissal Type",
                  titlefont={'size': 30},
                  )
fig.show()

In [57]:
len(df_warner[df_warner['batsman_runs']==4])

510

In [58]:
len(df_warner[df_warner['batsman_runs']==6])

195

In [59]:
df_warner['total_runs'].sum()

5522

In [60]:
def count(df_warner,runs):
    return len(df_warner[df_warner['batsman_runs']==runs])*runs

In [61]:
print("Runs scored from 1's :",count(df_warner,1))
print("Runs scored from 2's :",count(df_warner,2))
print("Runs scored from 3's :",count(df_warner,3))
print("Runs scored from 4's :",count(df_warner,4))
print("Runs scored from 6's :",count(df_warner,6))

Runs scored from 1's : 1348
Runs scored from 2's : 634
Runs scored from 3's : 57
Runs scored from 4's : 2040
Runs scored from 6's : 1170


In [62]:
values=[count(df_warner,1),count(df_warner,2),count(df_warner,3),count(df_warner,4),count(df_warner,6)]
labels=[1,2,3,4,6]
fig = go.Figure(data=[go.Pie(labels=labels,values=values,hole=.3)])
fig.update_traces(hoverinfo='label+percent', textinfo='label+value', textfont_size=20,
                  marker=dict(colors=colors, line=dict(color='#000000', width=3)))
fig.update_layout(title="David Warner total runs contribution",
                  titlefont={'size': 30},
                  )
fig.show()

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
    Interesting fact is that <b>David Warner</b> has similar scoring style as <b>Virat Kohli</b>
</p>
</div>

<a id="17">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">17) Innings wise comparision :</h1>



In [63]:
runs=deliveries_data.groupby(['id','inning','batting_team'])[['total_runs']].sum().reset_index()
runs.drop('id',axis=1,inplace=True)
runs.head()

inning                 batting_team  total_runs
0       1        Kolkata Knight Riders         222
1       2  Royal Challengers Bangalore          82
2       1          Chennai Super Kings         240
3       2              Kings XI Punjab         207
4       1             Rajasthan Royals         129

In [64]:
inning1=runs[runs['inning']==1]
inning2=runs[runs['inning']==2]

In [65]:
fig = px.box(y='total_runs',x='batting_team',data_frame=inning1,color='batting_team')

fig.update_layout(title="Batting First",
                  titlefont={'size': 26},template='simple_white'
                  )
fig.show()

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Royal Challengers Bangalore and Mumbai Indians median value is better than other teams while batting first.<br>
Royal Challengers Bangalore had scored 250+ in a single match and is the only team to achieve that feat.
</p>
</div>



<p style = "font-size:20px; font-weight : normal; color : #0331A8;">Batting second :</p>




In [66]:
fig = px.box(y='total_runs',x='batting_team',data_frame=inning2,color='batting_team')

fig.update_layout(title="Batting Second",
                  titlefont={'size': 26},template='simple_white'
                  )
fig.show()

<a id="18">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">18) Scored 200+ runs :</h1>


In [67]:
high_scores=deliveries_data.groupby(['id', 'inning','batting_team','bowling_team'])['total_runs'].sum().reset_index() 
score_200=high_scores[high_scores['total_runs']>=200]
score_200.head(5)

id  inning           batting_team                 bowling_team  \
0   335982       1  Kolkata Knight Riders  Royal Challengers Bangalore   
2   335983       1    Chennai Super Kings              Kings XI Punjab   
3   335983       2        Kings XI Punjab          Chennai Super Kings   
14  335989       1    Chennai Super Kings               Mumbai Indians   
15  335989       2         Mumbai Indians          Chennai Super Kings   

    total_runs  
0          222  
2          240  
3          207  
14         208  
15         202

In [68]:
x1=score_200['batting_team'].value_counts()
x1=pd.DataFrame(x1)
x1.style.background_gradient(cmap='PuBu')

In [69]:
colors = ['turquoise',] * 11
colors[0] = 'crimson'
fig=px.bar(x=x1.index,y=x1['batting_team'],labels=dict(x="Team Name",y="Count"),)
fig.update_layout(title="Total count of 200+ by batting team",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Royal Challengers Bangalore had scored the most 200+ score (18 times), followed by Chennai Super Kings who had scored 17 times.
</p>
</div>


<a id="19">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">19) Conceded 200+ runs :</h1>


In [70]:
z=score_200['bowling_team'].value_counts()
z=pd.DataFrame(z)
z.style.background_gradient(cmap='PuBu')



In [71]:
colors = ['turquoise',] * 13
colors[0] = 'crimson'
fig=px.bar(x=z.index,y=z['bowling_team'],labels=dict(x="Team Name",y="Count"),)
fig.update_layout(title="Total count of 200+ conceded by bowling team",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Kings XI Punjab has conceded 200+ runs 20 times, followed by Royal Challengers Bangalore (17)
</p>
</div>

<a id="20">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">20) Highest runs in an innings :</h1>



In [72]:
high_200=deliveries_data.groupby(['id', 'inning','batting_team','bowling_team'])['total_runs'].sum().reset_index()
high_200.set_index(['id'],inplace=True)

In [73]:
high_200['total_runs'].max()

263

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
In season 2013, Royal Challengers Bangalore scored 263/5 against Pune Warriors India.
</p>
</div>

<a id="21">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">21) Biggest win in terms of run margin :</h1>


In [74]:
match_data[match_data['result_margin']==match_data['result_margin'].max()]

id   city        date player_of_match             venue  \
620  1082635  Delhi  2017-05-06     LMP Simmons  Feroz Shah Kotla   

     neutral_venue             team1           team2       toss_winner  \
620              0  Delhi Daredevils  Mumbai Indians  Delhi Daredevils   

    toss_decision          winner result  result_margin eliminator method  \
620         field  Mumbai Indians   runs          146.0          N    NaN   

         umpire1    umpire2  Season toss_win_game_win  
620  Nitin Menon  CK Nandan    2017                No

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
In season 2017, Mumbai Indians had defeated Delhi Daredevils by a huge margin of 146 runs.
</p>
</div>


<a id="22">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">22) Most balls played by a batsman:</h1>


In [75]:
balls_played=deliveries_data.groupby(['batsman'])['ball'].count().reset_index()
balls_played.sort_values(by='ball',ascending=False).head(10).style.background_gradient(cmap='PuBu')


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Virat kohli had played the most balls.<br> 
David Warner and Chris Gayle are the only two foreign players in this top 10 list.
</p>
</div>

<a id="23">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">23) Top 10 run scorer of all time :</h1>


In [76]:
runs=deliveries_data.groupby(['batsman'])['batsman_runs'].sum().reset_index()
runs.columns=['Batsman','runs']
y=runs.sort_values(by='runs',ascending=False).head(10).reset_index().drop('index',axis=1)
y.style.background_gradient(cmap='PuBu')

In [77]:
colors = ['turquoise',] * 13
colors[0] = 'crimson'
fig=px.bar(x=y['Batsman'],y=y['runs'],labels=dict(x="Player",y="Total Runs"),)
fig.update_layout(title="Top 10 leading run-scrorer",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Virat Kohli is the leading run scorer in IPL.<br>
One interesting thing to notice that MS Dhoni is the only player in this list who bats down the order.
</p>
</div>

<a id="24">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">24) Most number of 4's :</h1>


In [78]:
balls_played=balls_played.merge(runs,left_on='batsman',right_on='Batsman',how='outer')
four=deliveries_data[deliveries_data['batsman_runs']==4]
runs_4=four.groupby('batsman')['batsman_runs'].count().reset_index()
runs_4.columns=['Batsman','4s']
runs_4.sort_values(by='4s',ascending=False).head(10).reset_index().drop('index',axis=1).style.background_gradient(cmap='PuBu')

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Shikhar Dhawan holds the record for most number of 4's
</p>
</div>

<a id="25">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">25) Most number of 6's :</h1>


In [79]:
six=deliveries_data.groupby('batsman')['batsman_runs'].agg(lambda x: (x==6).sum()).reset_index()
six.columns=['Batsman','6s']
six.sort_values(by='6s',ascending=False).head(10).reset_index().drop('index',axis=1).style.background_gradient(cmap='PuBu')

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
"The Universe Boss" Chris Gayle had smashed 349 sixes, most by any batsman.
</p>
</div>

<a id="26">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">26) Highest Strike rate (minimum 100 balls):</h1>


In [80]:
player=pd.concat([runs,balls_played.iloc[:,1],runs_4.iloc[:,1],six.iloc[:,1]],axis=1)
player['strike_rate']=player['runs']/player['ball']*100
player['4s'].fillna(0,inplace=True)
player.isnull().values.any()

False

In [81]:
player.sort_values(by='strike_rate',ascending=False).head(10)

Batsman  runs  ball     4s   6s  strike_rate
72        B Stanlake     5     2    3.0    0   250.000000
504         Umar Gul    39    19    0.0    5   205.263158
395         RS Sodhi     4     2    1.0    0   200.000000
470    Shahid Afridi    81    46    0.0    6   176.086957
175       I Malhotra     7     4   13.0    0   175.000000
498     TU Deshpande    21    12    0.0    1   175.000000
33        AD Russell  1517   882   24.0  129   171.995465
253        LJ Wright   106    63    4.0    3   168.253968
57       Abdul Samad   111    66   28.0    6   168.181818
235  KMDN Kulasekara     5     3  156.0    0   166.666667

In [82]:
sr=player[player.ball > 100]
sr.sort_values(by='strike_rate',ascending=False).head(10)


Batsman  runs  ball     4s   6s  strike_rate
33      AD Russell  1517   882   24.0  129   171.995465
217      K Gowtham   186   113  247.0   12   164.601770
80     BCJ Cutting   238   146   40.0   19   163.013699
317       N Pooran   521   323    6.0   39   161.300310
453      SP Narine   892   573    0.0   52   155.671902
293         MM Ali   309   199   23.0   23   155.276382
97       CH Morris   551   360  116.0   30   153.055556
192      JC Archer   195   128   18.0   14   152.343750
106  CR Brathwaite   181   120   11.0   16   150.833333
88    Bipul Sharma   187   124    5.0    9   150.806452

In [83]:
reqsr=sr.drop(columns=['runs','ball','4s','6s'],axis=1)
reqsr.sort_values(by='strike_rate',ascending=False).head(10).style.background_gradient(cmap='PuBu')

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Andre Russel has the highest strike rate, followed by K. Gowtham and B. Cutting.
</p>
</div>

<a id="27">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">27) Highest wicket-taker :</h1>


In [84]:
deliveries_data['dismissal_kind'].unique()
dismissal_kinds = ['caught', 'bowled', 'lbw', 'caught and bowled',
       'stumped', 'hit wicket']
hwt=deliveries_data[deliveries_data["dismissal_kind"].isin(dismissal_kinds)]
bo=hwt['bowler'].value_counts()

In [85]:
colors = ['turquoise',] * 13
colors[0] = 'crimson'
fig=px.bar(x=bo[:10].index,y=bo[:10],labels=dict(x="Bowler",y="Total Wickets"),)
fig.update_layout(title="Leading wicket-takers",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
L. Malinga is the leading wicket taker in IPL.<br>
6 out of top 10 are spin bowlers.
</p>
</div>

<a id="28">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">28) Total count of matches played in differnt stadiums :</h1>



In [86]:
colors = ['turquoise',] * 13
colors[0] = 'crimson'
fig=px.bar(x=match_data['venue'].value_counts()[:10].index,y=match_data['venue'].value_counts()[:10],labels=dict(x="Venue",y="Match count"),)
fig.update_layout(title="Matches played at different stadiums",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()



<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Eden Gardens has hosted most number of matches.
</p>
</div>


<a id="29">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">29) Man of the Match award :</h1>


In [87]:
colors = ['turquoise',] * 11
colors[0] = 'crimson'
fig=px.bar(x=match_data.player_of_match.value_counts()[:10].index,y=match_data.player_of_match.value_counts()[:10],labels=dict(x="Players",y="Count"),)
fig.update_layout(title="Top 10 MOM awardee",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
<b>AB de Villiers</b> (23) had won the most MOM awards, followed by Chris Gayle (22)
</p>
</div>


<a id="30">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">30) Total number of fours in each season :</h1>



In [88]:
data_4 = match_data['Season'].unique()

fours_list = []
for var in data_4:
    new_df = match_data[match_data['Season']==var]
    total_fours = 0
    for i in new_df['id'].values:
        temp_df = deliveries_data[deliveries_data['id']==i]
        fours = temp_df[temp_df['batsman_runs']==4]['batsman_runs'].count()
        total_fours+=fours
    fours_list.append(total_fours)
    

colors = ['turquoise',] * 14
colors[5] = 'crimson'
fig=px.bar(x=data_4, y=fours_list,labels=dict(x="Season",y="Total Fours"),)
fig.update_layout(title="Total number of Fours in each season",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Highest number of four in a season was is 2013 season while season 2009 had the lowest count of 4's.
</p>
</div>


<a id="31">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">31) Total number of sixes in each season :</h1>


In [89]:

data_6 = match_data['Season'].unique()

# Getting total sixes from each season by check id from matches dataset in deliveries dataset.
sixes_list = []
for var in data_6:
    new_df = match_data[match_data['Season']==var]
    total_sixes = 0
    for i in new_df['id'].values:
        temp_df = deliveries_data[deliveries_data['id']==i]
        sixes = temp_df[temp_df['batsman_runs']==6]['batsman_runs'].count()
        total_sixes+=sixes
    sixes_list.append(total_sixes)
    
colors = ['turquoise',] * 14
colors[-4] = 'crimson'
fig=px.bar(x=data_4, y=sixes_list,labels=dict(x="Season",y="Total Sixes"),)
fig.update_layout(title="Total number of Sixes in each season",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
In season 2018, the maximum number of sixes were hit while the lowest was observed in season 2009.
</p>
</div>

<a id="32">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">32) Total runs scored from boundaries in each season :</h1>


In [90]:
runs4=np.dot(fours_list,4)
runs6=np.dot(sixes_list,6)

In [91]:
k=runs4+runs6
Y=match_data['Season'].unique()
colors = ['turquoise',] * 14
colors[5] = 'crimson'
fig=px.bar(x=Y,y=k,labels=dict(x="Season",y="Total runs"),)
fig.update_layout(title="Total number of runs scored from boundaries in each season",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()



<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Total run scored from boundaries is lowest in season 2009 and highest in season 2013.
</p>
</div>


<a id="33">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">33) Total contribution of runs from boundaries in each season :</h1>


In [92]:
totruns=np.array(season['total_runs'])
res=(k/totruns)*100

In [93]:
res

array([58.81697051, 50.88235294, 54.82400339, 54.35378652, 53.63203135,
       54.3809059 , 55.6983447 , 57.71328824, 54.95705652, 56.87037136,
       59.49449776, 58.32989691, 55.50847458])

In [94]:
colors = ['turquoise',] * 14
colors[10] = 'crimson'
fig=px.bar(x=Y,y=res,labels=dict(x="Season",y="Percentage"),)
fig.update_layout(title="Total contribution of runs from boundaries in each season",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
In season 2018, 59.49 % runs of the total runs came from boundaries while 50.88 % runs came from boundaries in season 2009 which is lowest till now.
</p>
</div>


<a id="34">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">34) Total runs scored by teams in first 6 overs :</h1>



In [95]:
team = deliveries_data['batting_team'].unique()
team_runs = []
for var in team:
    temp_df = deliveries_data[deliveries_data['batting_team']==var]
    temp_df = temp_df[temp_df['over'].isin([0,1,2,3,4,5])]
    runs = temp_df['total_runs'].sum()
    team_runs.append(runs)
team = pd.DataFrame(data=team_runs, index=team,columns=['Runs In First 6 Overs'])
#team.sort_values('Runs In First 6 Overs', ascending=False, inplace=True)
team.index.name = 'Team'

colors = ['turquoise',] * 15
colors[6] = 'crimson'
fig=px.bar(x=team.index,y=team['Runs In First 6 Overs'],labels=dict(x="Team Name",y="Total runs"),)
fig.update_layout(title="Total runs scored by teams in thier first 6 overs",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
<b>Mumbai Indians</b> had scored the  most runs in first 6 overs, followed by Kings XI Punjab.
</p>
</div>


<a id="35">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">35) Total runs scored by teams in last 4 overs :</h1>



In [96]:
team1 = deliveries_data['batting_team'].unique()
team_runs1 = []
for var in team1:
    temp_df = deliveries_data[deliveries_data['batting_team']==var]
    temp_df = temp_df[temp_df['over'].isin([19,18,17,16])]
    runs1 = temp_df['total_runs'].sum()
    team_runs1.append(runs1)
team1 = pd.DataFrame(data=team_runs1, index=team1,columns=['Runs In Last 4 Overs'])
# team.sort_values('Runs In First 6 Overs', ascending=False, inplace=True)
team1.index.name = 'Team'
colors = ['turquoise',] * 15
colors[6] = 'crimson'
fig=px.bar(x=team1.index,y=team1['Runs In Last 4 Overs'],labels=dict(x="Team Name",y="Total runs"),)
fig.update_layout(title="Total runs scored by teams in thier last 4 overs",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Mumbai Indians had scored most runs in last 4 overs, followed by Royal Challengers Bangalore.
</p>
</div>

<a id="36">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">36) Highest scoring run-rate in first 6 overs :</h1>



In [97]:
played1=played.merge(team,left_on='Team Name',right_on='Team',how='inner')
played3=played1.merge(team1,left_on='Team Name',right_on='Team',how='inner')
mintoover=np.dot(played3['Total Matches played'],6)
mintoover1=np.dot(played3['Total Matches played'],4)
played3['RR in first 6 overs']=(played3['Runs In First 6 Overs']/mintoover)
played3['RR in last 4 overs']=(played3['Runs In Last 4 Overs']/mintoover1)
played3

Team Name  Total Matches played  Wins      % Win  \
0           Chennai Super Kings                   178   106  59.550562   
1               Deccan Chargers                    75    29  38.666667   
2                Delhi Capitals                    33    19  57.575758   
3              Delhi Daredevils                   161    67  41.614907   
4                 Gujarat Lions                    30    13  43.333333   
5               Kings XI Punjab                   190    88  46.315789   
6          Kochi Tuskers Kerala                    14     6  42.857143   
7         Kolkata Knight Riders                   192    99  51.562500   
8                Mumbai Indians                   203   120  59.113300   
9                 Pune Warriors                    46    12  26.086957   
10             Rajasthan Royals                   161    81  50.310559   
11       Rising Pune Supergiant                    16    10  62.500000   
12      Rising Pune Supergiants                    14     5  35.714286   
13  Royal Challengers Bangalore                   195    91  46.666667   
14          Sunrisers Hyderabad                   124    66  53.225806   

    Runs In First 6 Overs  Runs In Last 4 Overs  RR in first 6 overs  \
0                    8048                  6655             7.535581   
1                    3417                  2539             7.593333   
2                    1560                  1160             7.878788   
3                    7349                  5043             7.607660   
4                    1553                   921             8.627778   
5                    8907                  6227             7.813158   
6                     680                   337             8.095238   
7                    8871                  6224             7.700521   
8                    9204                  7538             7.556650   
9                    1895                  1360             6.865942   
10                   7151                  5043             7.402692   
11                    785                   555             8.177083   
12                    638                   443             7.595238   
13                   8699                  6787             7.435043   
14                   5917                  4155             7.952957   

    RR in last 4 overs  
0             9.346910  
1             8.463333  
2             8.787879  
3             7.830745  
4             7.675000  
5             8.193421  
6             6.017857  
7             8.104167  
8             9.283251  
9             7.391304  
10            7.830745  
11            8.671875  
12            7.910714  
13            8.701282  
14            8.377016

In [98]:
colors = ['turquoise',] * 15
colors[4] = 'crimson'
fig=px.bar(x=played3['Team Name'],y=played3['RR in first 6 overs'],labels=dict(x="Team Name",y="Run Rate"),)
fig.update_layout(title="Run Rate in first 6 overs",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Gujarat Lions has the highest scoring run-rate in first 6 overs, followed by Rising Pune Supergiant.
</p>
</div>


<a id="37">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">37) Highest scoring rate in last 4 overs :</h1>

In [99]:
colors = ['turquoise',] * 15
colors[0] = 'crimson'
fig=px.bar(x=played3['Team Name'],y=played3['RR in last 4 overs'],labels=dict(x="Team Name",y="Run Rate"),)
fig.update_layout(title="Run Rate in last 4 overs",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
<b>Chennai Super Kings</b> has the highest scoring run-rate in last 4 overs, followed by Mumbai Indians.
</p>
</div>


<a id="38">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">38) Top Fielders :</h1>



In [100]:
deliveries_data['dismissal_kind'].unique()
dismissal_kind = ['caught', 'bowled', 'lbw', 'caught and bowled','stumped', 'hit wicket']
hwtt=deliveries_data[deliveries_data["dismissal_kind"].isin(dismissal_kinds)]
boo=hwtt['fielder'].value_counts()

In [101]:
colors = ['turquoise',] * 13
colors[0] = 'crimson'
fig=px.bar(x=boo[:10].index,y=bo[:10],labels=dict(x="Fielder",y="Wickets"),)
fig.update_layout(title="Leading fielders",
                  titlefont={'size': 26},template='simple_white'     
                  )
fig.update_traces(marker_line_color='black',
                  marker_line_width=2.5, opacity=1,marker_color=colors)
fig.show()


<div class="alert alert-block alert-info"><p style='color:black;'> 📌
<b>MS Dhoni</b> was the top fielder with 170 wickets followed by <b>Dinesh Karthik</b> with 160 wickets
</p>
</div>


<a id="39">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">39) Smallest win in terms of run margin :</h1>


In [102]:
match_data[match_data['result_margin']==match_data['result_margin'].min()]

id          city        date player_of_match  \
46    336028        Mumbai  2008-05-21        SE Marsh   
104   392229  Johannesburg  2009-05-17    Yuvraj Singh   
285   548345         Delhi  2012-04-29        V Sehwag   
291   548351          Pune  2012-05-03      SL Malinga   
459   829707       Chennai  2015-04-09         A Nehra   
500   829791       Kolkata  2015-05-09      AD Russell   
539   980945         Delhi  2016-04-27       CH Morris   
555   980977    Chandigarh  2016-05-09       SR Watson   
635  1082650     Hyderabad  2017-05-21       KH Pandya   
636  1136561        Mumbai  2018-04-07        DJ Bravo   
642  1136567     Hyderabad  2018-04-12     Rashid Khan   
734  1178414     Bengaluru  2019-04-21        PA Patel   
755  1181768     Hyderabad  2019-05-12       JJ Bumrah   

                                                 venue  neutral_venue  \
46                                    Wankhede Stadium              0   
104                              New Wanderers Stadium              1   
285                                   Feroz Shah Kotla              0   
291                         Subrata Roy Sahara Stadium              0   
459                    MA Chidambaram Stadium, Chepauk              0   
500                                       Eden Gardens              0   
539                                   Feroz Shah Kotla              0   
555  Punjab Cricket Association IS Bindra Stadium, ...              0   
635          Rajiv Gandhi International Stadium, Uppal              0   
636                                   Wankhede Stadium              0   
642          Rajiv Gandhi International Stadium, Uppal              0   
734                              M.Chinnaswamy Stadium              0   
755          Rajiv Gandhi International Stadium, Uppal              0   

                           team1                        team2  \
46                Mumbai Indians              Kings XI Punjab   
104              Deccan Chargers              Kings XI Punjab   
285             Delhi Daredevils             Rajasthan Royals   
291                Pune Warriors               Mumbai Indians   
459          Chennai Super Kings             Delhi Daredevils   
500        Kolkata Knight Riders              Kings XI Punjab   
539             Delhi Daredevils                Gujarat Lions   
555              Kings XI Punjab  Royal Challengers Bangalore   
635               Mumbai Indians       Rising Pune Supergiant   
636               Mumbai Indians          Chennai Super Kings   
642          Sunrisers Hyderabad               Mumbai Indians   
734  Royal Challengers Bangalore          Chennai Super Kings   
755               Mumbai Indians          Chennai Super Kings   

             toss_winner toss_decision                       winner   result  \
46        Mumbai Indians         field              Kings XI Punjab     runs   
104      Deccan Chargers         field              Kings XI Punjab     runs   
285     Delhi Daredevils           bat             Delhi Daredevils     runs   
291       Mumbai Indians           bat               Mumbai Indians     runs   
459     Delhi Daredevils         field          Chennai Super Kings     runs   
500      Kings XI Punjab           bat        Kolkata Knight Riders  wickets   
539     Delhi Daredevils         field                Gujarat Lions     runs   
555      Kings XI Punjab         field  Royal Challengers Bangalore     runs   
635       Mumbai Indians           bat               Mumbai Indians     runs   
636  Chennai Super Kings         field          Chennai Super Kings  wickets   
642  Sunrisers Hyderabad         field          Sunrisers Hyderabad  wickets   
734  Chennai Super Kings         field  Royal Challengers Bangalore     runs   
755       Mumbai Indians           bat               Mumbai Indians     runs   

     result_margin eliminator method         umpire1          umpire2  Season  \
46             1.0          N    NaN       BF Bowden   GA Pra

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
In season 2019, Mumbai Indians had defeated Chennai Super Kings by a smallest margin of 1 run.
</p>
</div>


<a id="40">
<h1 style = "font-family: Snell Roundhand;font-weight: 500;font-size: 30px; font-style: normal; background-color: #FFFB30; color :black;">40) Top Most Dismissmal Reasons</h1>



In [103]:
values = deliveries_data['dismissal_kind'].value_counts()
labels=df_warner['dismissal_kind'].value_counts().index
fig = go.Figure(data=[go.Pie(labels=labels,values=values,hole=.3)])
fig.update_traces(hoverinfo='label+percent', textinfo='label', textfont_size=20,
                  marker=dict(colors=colors, line=dict(color='#000000', width=3)))
fig.update_layout(title="Dismissal Reasons",
                  titlefont={'size': 25},
                  )
fig.show()

<div class="alert alert-block alert-info"><p style='color:black;'> 📌
Interestingly,  60 out of 100 times batsmen lose their wickets by getting caught
</p>
</div>


In [104]:
data=match_data.merge(deliveries_data,on='id')
data

id       city        date player_of_match  \
0        335982  Bangalore  2008-04-18     BB McCullum   
1        335982  Bangalore  2008-04-18     BB McCullum   
2        335982  Bangalore  2008-04-18     BB McCullum   
3        335982  Bangalore  2008-04-18     BB McCullum   
4        335982  Bangalore  2008-04-18     BB McCullum   
...         ...        ...         ...             ...   
193463  1237181      Dubai  2020-11-10        TA Boult   
193464  1237181      Dubai  2020-11-10        TA Boult   
193465  1237181      Dubai  2020-11-10        TA Boult   
193466  1237181      Dubai  2020-11-10        TA Boult   
193467  1237181      Dubai  2020-11-10        TA Boult   

                                      venue  neutral_venue  \
0                     M Chinnaswamy Stadium              0   
1                     M Chinnaswamy Stadium              0   
2                     M Chinnaswamy Stadium              0   
3                     M Chinnaswamy Stadium              0   
4                     M Chinnaswamy Stadium              0   
...                                     ...            ...   
193463  Dubai International Cricket Stadium              0   
193464  Dubai International Cricket Stadium              0   
193465  Dubai International Cricket Stadium              0   
193466  Dubai International Cricket Stadium              0   
193467  Dubai International Cricket Stadium              0   

                              team1                  team2  \
0       Royal Challengers Bangalore  Kolkata Knight Riders   
1       Royal Challengers Bangalore  Kolkata Knight Riders   
2       Royal Challengers Bangalore  Kolkata Knight Riders   
3       Royal Challengers Bangalore  Kolkata Knight Riders   
4       Royal Challengers Bangalore  Kolkata Knight Riders   
...                             ...                    ...   
193463               Delhi Capitals         Mumbai Indians   
193464               Delhi Capitals         Mumbai Indians   
193465               Delhi Capitals         Mumbai Indians   
193466               Delhi Capitals         Mumbai Indians   
193467               Delhi Capitals         Mumbai Indians   

                        toss_winner toss_decision  ... extra_runs total_runs  \
0       Royal Challengers Bangalore         field  ...          0          1   
1       Royal Challengers Bangalore         field  ...          0          1   
2       Royal Challengers Bangalore         field  ...          0          0   
3       Royal Challengers Bangalore         field  ...          0          1   
4       Royal Challengers Bangalore         field  ...          0          1   
...                             ...           ...  ...        ...        ...   
193463               Delhi Capitals           bat  ...          0          0   
193464               Delhi Capitals           bat  ...          0          1   
193465               Delhi Capitals           bat  ...          1          1   
193466               Delhi Capitals           bat  ...          0          1   
193467               Delhi Capitals           bat  ...          0          1   

        non_boundary is_wicket dismissal_kind player_dismissed fielder  \
0                  0         0            NaN              NaN     NaN   
1                  0         0            NaN              NaN     NaN   
2                  0         0            NaN              NaN     NaN   
3                  0         0            NaN              NaN     NaN   
4                  0         0            NaN              NaN     NaN   
...              ...       ...            ...              ...     ...   
193463             0         0            NaN              NaN     NaN   
193464             0         0            NaN              NaN     NaN   
193465             0         0            NaN              NaN     NaN   
193466             0         0            NaN              NaN     NaN   
193467             0         0            NaN      

In [105]:
data.drop(['date', 'city','player_of_match','neutral_venue','toss_winner','toss_decision','method', 'umpire1', 'umpire2','batsman', 'non_striker', 'bowler',
        'batsman_runs','extra_runs','result', 'non_boundary','eliminator','result_margin','dismissal_kind', 'player_dismissed', 'fielder', 'extras_type'], axis='columns',inplace=True)
data.head()

id                  venue                        team1  \
0  335982  M Chinnaswamy Stadium  Royal Challengers Bangalore   
1  335982  M Chinnaswamy Stadium  Royal Challengers Bangalore   
2  335982  M Chinnaswamy Stadium  Royal Challengers Bangalore   
3  335982  M Chinnaswamy Stadium  Royal Challengers Bangalore   
4  335982  M Chinnaswamy Stadium  Royal Challengers Bangalore   

                   team2                 winner  Season toss_win_game_win  \
0  Kolkata Knight Riders  Kolkata Knight Riders    2008                No   
1  Kolkata Knight Riders  Kolkata Knight Riders    2008                No   
2  Kolkata Knight Riders  Kolkata Knight Riders    2008                No   
3  Kolkata Knight Riders  Kolkata Knight Riders    2008                No   
4  Kolkata Knight Riders  Kolkata Knight Riders    2008                No   

   inning  over  ball  total_runs  is_wicket           batting_team  \
0       1     6     5           1          0  Kolkata Knight Riders   
1       1     6     6           1          0  Kolkata Knight Riders   
2       1     7     1           0          0  Kolkata Knight Riders   
3       1     7     2           1          0  Kolkata Knight Riders   
4       1     7     3           1          0  Kolkata Knight Riders   

                  bowling_team  
0  Royal Challengers Bangalore  
1  Royal Challengers Bangalore  
2  Royal Challengers Bangalore  
3  Royal Challengers Bangalore  
4  Royal Challengers Bangalore

In [106]:
data1=data.groupby(['id','inning']).sum()['total_runs']
data1


id       inning
335982   1         222
         2          82
335983   1         240
         2         207
335984   1         129
                  ... 
1237178  2         132
1237180  1         189
         2         172
1237181  1         156
         2         157
Name: total_runs, Length: 1630, dtype: int64

In [107]:
data1=data1.reset_index()
data1

id  inning  total_runs
0      335982       1         222
1      335982       2          82
2      335983       1         240
3      335983       2         207
4      335984       1         129
...       ...     ...         ...
1625  1237178       2         132
1626  1237180       1         189
1627  1237180       2         172
1628  1237181       1         156
1629  1237181       2         157

[1630 rows x 3 columns]

In [108]:
data1=data1[data1.inning==1]
data1

id  inning  total_runs
0      335982       1         222
2      335983       1         240
4      335984       1         129
6      335985       1         165
8      335986       1         110
...       ...     ...         ...
1620  1216547       1         201
1622  1237177       1         200
1624  1237178       1         131
1626  1237180       1         189
1628  1237181       1         156

[816 rows x 3 columns]

In [109]:
data1['Target']=data1['total_runs']+1
data1.drop(['total_runs'],axis='columns',inplace=True)
data1

id  inning  Target
0      335982       1     223
2      335983       1     241
4      335984       1     130
6      335985       1     166
8      335986       1     111
...       ...     ...     ...
1620  1216547       1     202
1622  1237177       1     201
1624  1237178       1     132
1626  1237180       1     190
1628  1237181       1     157

[816 rows x 3 columns]

In [110]:
data=data.merge(data1,on='id')
data

id                                venue  \
0        335982                M Chinnaswamy Stadium   
1        335982                M Chinnaswamy Stadium   
2        335982                M Chinnaswamy Stadium   
3        335982                M Chinnaswamy Stadium   
4        335982                M Chinnaswamy Stadium   
...         ...                                  ...   
193463  1237181  Dubai International Cricket Stadium   
193464  1237181  Dubai International Cricket Stadium   
193465  1237181  Dubai International Cricket Stadium   
193466  1237181  Dubai International Cricket Stadium   
193467  1237181  Dubai International Cricket Stadium   

                              team1                  team2  \
0       Royal Challengers Bangalore  Kolkata Knight Riders   
1       Royal Challengers Bangalore  Kolkata Knight Riders   
2       Royal Challengers Bangalore  Kolkata Knight Riders   
3       Royal Challengers Bangalore  Kolkata Knight Riders   
4       Royal Challengers Bangalore  Kolkata Knight Riders   
...                             ...                    ...   
193463               Delhi Capitals         Mumbai Indians   
193464               Delhi Capitals         Mumbai Indians   
193465               Delhi Capitals         Mumbai Indians   
193466               Delhi Capitals         Mumbai Indians   
193467               Delhi Capitals         Mumbai Indians   

                       winner  Season toss_win_game_win  inning_x  over  ball  \
0       Kolkata Knight Riders    2008                No         1     6     5   
1       Kolkata Knight Riders    2008                No         1     6     6   
2       Kolkata Knight Riders    2008                No         1     7     1   
3       Kolkata Knight Riders    2008                No         1     7     2   
4       Kolkata Knight Riders    2008                No         1     7     3   
...                       ...     ...               ...       ...   ...   ...   
193463         Mumbai Indians    2020                No         1    12     5   
193464         Mumbai Indians    2020                No         1    12     6   
193465         Mumbai Indians    2020                No         1    13     1   
193466         Mumbai Indians    2020                No         1    13     2   
193467         Mumbai Indians    2020                No         1    13     3   

        total_runs  is_wicket           batting_team  \
0                1          0  Kolkata Knight Riders   
1                1          0  Kolkata Knight Riders   
2                0          0  Kolkata Knight Riders   
3                1          0  Kolkata Knight Riders   
4                1          0  Kolkata Knight Riders   
...            ...        ...                    ...   
193463           0          0         Delhi Capitals   
193464           1          0         Delhi Capitals   
193465           1          0         Delhi Capitals   
193466           1          0         Delhi Capitals   
193467           1          0         Delhi Capitals   

                       bowling_team  inning_y  Target  
0       Royal Challengers Bangalore         1     223  
1       Royal Challengers Bangalore         1     223  
2       Royal Challengers Bangalore         1     223  
3       Royal Challengers Bangalore         1     223  
4       Royal Challengers Bangalore         1     223  
...                             ...       ...     ...  
193463               Mumbai Indians         1     157  
193464               Mumbai Indians         1     157  
193465               Mumbai Indians         1     157  
193466               Mumbai Indians         1     157  
193467               Mumbai Indians         1     157  

[193468 rows x 16 columns]

In [111]:
data=data[(data.inning_x==2)]
data

id                                venue  \
121      335982                M Chinnaswamy Stadium   
122      335982                M Chinnaswamy Stadium   
123      335982                M Chinnaswamy Stadium   
124      335982                M Chinnaswamy Stadium   
125      335982                M Chinnaswamy Stadium   
...         ...                                  ...   
193372  1237181  Dubai International Cricket Stadium   
193373  1237181  Dubai International Cricket Stadium   
193374  1237181  Dubai International Cricket Stadium   
193375  1237181  Dubai International Cricket Stadium   
193376  1237181  Dubai International Cricket Stadium   

                              team1                  team2  \
121     Royal Challengers Bangalore  Kolkata Knight Riders   
122     Royal Challengers Bangalore  Kolkata Knight Riders   
123     Royal Challengers Bangalore  Kolkata Knight Riders   
124     Royal Challengers Bangalore  Kolkata Knight Riders   
125     Royal Challengers Bangalore  Kolkata Knight Riders   
...                             ...                    ...   
193372               Delhi Capitals         Mumbai Indians   
193373               Delhi Capitals         Mumbai Indians   
193374               Delhi Capitals         Mumbai Indians   
193375               Delhi Capitals         Mumbai Indians   
193376               Delhi Capitals         Mumbai Indians   

                       winner  Season toss_win_game_win  inning_x  over  ball  \
121     Kolkata Knight Riders    2008                No         2     6     2   
122     Kolkata Knight Riders    2008                No         2     6     3   
123     Kolkata Knight Riders    2008                No         2     6     4   
124     Kolkata Knight Riders    2008                No         2     6     5   
125     Kolkata Knight Riders    2008                No         2     6     6   
...                       ...     ...               ...       ...   ...   ...   
193372         Mumbai Indians    2020                No         2    17     6   
193373         Mumbai Indians    2020                No         2    18     1   
193374         Mumbai Indians    2020                No         2    18     2   
193375         Mumbai Indians    2020                No         2    18     3   
193376         Mumbai Indians    2020                No         2    18     4   

        total_runs  is_wicket                 batting_team  \
121              0          0  Royal Challengers Bangalore   
122              1          0  Royal Challengers Bangalore   
123              1          0  Royal Challengers Bangalore   
124              1          0  Royal Challengers Bangalore   
125              0          0  Royal Challengers Bangalore   
...            ...        ...                          ...   
193372           1          0               Mumbai Indians   
193373           1          0               Mumbai Indians   
193374           1          0               Mumbai Indians   
193375           0          1               Mumbai Indians   
193376           1          0               Mumbai Indians   

                 bowling_team  inning_y  Target  
121     Kolkata Knight Riders         1     223  
122     Kolkata Knight Riders         1     223  
123     Kolkata Knight Riders         1     223  
124     Kolkata Knight Riders         1     223  
125     Kolkata Knight Riders         1     223  
...                       ...       ...     ...  
193372         Delhi Capitals         1     157  
193373         Delhi Capitals         1     157  
193374         Delhi Capitals         1     157  
193375         Delhi Capitals         1     157  
193376         Delhi Capitals         1     157  

[93277 rows x 16 columns]

In [112]:
data.drop(['inning_x','inning_y','team1','team2'],axis='columns',inplace=True)
data.rename(columns={"total_runs":"Run_on_this_ball"},inplace=True)

In [113]:
data

id                                venue                 winner  \
121      335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
122      335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
123      335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
124      335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
125      335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
...         ...                                  ...                    ...   
193372  1237181  Dubai International Cricket Stadium         Mumbai Indians   
193373  1237181  Dubai International Cricket Stadium         Mumbai Indians   
193374  1237181  Dubai International Cricket Stadium         Mumbai Indians   
193375  1237181  Dubai International Cricket Stadium         Mumbai Indians   
193376  1237181  Dubai International Cricket Stadium         Mumbai Indians   

        Season toss_win_game_win  over  ball  Run_on_this_ball  is_wicket  \
121       2008                No     6     2                 0          0   
122       2008                No     6     3                 1          0   
123       2008                No     6     4                 1          0   
124       2008                No     6     5                 1          0   
125       2008                No     6     6                 0          0   
...        ...               ...   ...   ...               ...        ...   
193372    2020                No    17     6                 1          0   
193373    2020                No    18     1                 1          0   
193374    2020                No    18     2                 1          0   
193375    2020                No    18     3                 0          1   
193376    2020                No    18     4                 1          0   

                       batting_team           bowling_team  Target  
121     Royal Challengers Bangalore  Kolkata Knight Riders     223  
122     Royal Challengers Bangalore  Kolkata Knight Riders     223  
123     Royal Challengers Bangalore  Kolkata Knight Riders     223  
124     Royal Challengers Bangalore  Kolkata Knight Riders     223  
125     Royal Challengers Bangalore  Kolkata Knight Riders     223  
...                             ...                    ...     ...  
193372               Mumbai Indians         Delhi Capitals     157  
193373               Mumbai Indians         Delhi Capitals     157  
193374               Mumbai Indians         Delhi Capitals     157  
193375               Mumbai Indians         Delhi Capitals     157  
193376               Mumbai Indians         Delhi Capitals     157  

[93277 rows x 12 columns]

In [114]:
data.batting_team.unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Mumbai Indians', 'Chennai Super Kings', 'Deccan Chargers',
       'Pune Warriors', 'Kochi Tuskers Kerala', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

In [115]:
data.batting_team=data.batting_team.str.replace('Delhi Daredevils','Delhi Capitals')
data.bowling_team=data.bowling_team.str.replace('Delhi Daredevils','Delhi Capitals')
data.batting_team=data.batting_team.str.replace('Deccan Chargers','Sunrisers Hyderabad')
data.bowling_team=data.bowling_team.str.replace('Deccan Chargers','Sunrisers Hyderabad')

In [116]:
data.drop(data[data.batting_team=='Kochi Tuskers Kerala'].index,inplace=True)

In [117]:
data.drop(data[data.batting_team=='Pune Warriors'].index,inplace=True)
data.drop(data[data.batting_team=='Rising Pune Supergiants'].index,inplace=True)
data.drop(data[data.batting_team== 'Gujarat Lions'].index,inplace=True)
data.drop(data[data.batting_team=='Rising Pune Supergiant'].index,inplace=True)
batting1=data.batting_team.unique()
batting1

array(['Royal Challengers Bangalore', 'Kings XI Punjab', 'Delhi Capitals',
       'Kolkata Knight Riders', 'Rajasthan Royals', 'Mumbai Indians',
       'Chennai Super Kings', 'Sunrisers Hyderabad'], dtype=object)

In [118]:
len(batting1)

8

In [119]:
data.bowling_team.unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians', 'Sunrisers Hyderabad', 'Kings XI Punjab',
       'Royal Challengers Bangalore', 'Delhi Capitals',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants',
       'Gujarat Lions', 'Rising Pune Supergiant'], dtype=object)

In [120]:
data.drop(data[data.bowling_team=='Kochi Tuskers Kerala'].index,inplace=True)
data.drop(data[data.bowling_team=='Pune Warriors'].index,inplace=True)
data.drop(data[data.bowling_team=='Rising Pune Supergiants'].index,inplace=True)
data.drop(data[data.bowling_team== 'Gujarat Lions'].index,inplace=True)
data.drop(data[data.bowling_team=='Rising Pune Supergiant'].index,inplace=True)
bowling1=data.bowling_team.unique()
bowling1

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians', 'Sunrisers Hyderabad', 'Kings XI Punjab',
       'Royal Challengers Bangalore', 'Delhi Capitals'], dtype=object)

In [122]:
len(bowling1)

8

In [123]:
data.isna().sum()

id                    0
venue                 0
winner               27
Season                0
toss_win_game_win     0
over                  0
ball                  0
Run_on_this_ball      0
is_wicket             0
batting_team          0
bowling_team          0
Target                0
dtype: int64

In [124]:
data=data.dropna()
data.isna().sum()

id                   0
venue                0
winner               0
Season               0
toss_win_game_win    0
over                 0
ball                 0
Run_on_this_ball     0
is_wicket            0
batting_team         0
bowling_team         0
Target               0
dtype: int64

In [125]:
data['Ball_Number']=(data['over'])*6+data['ball']
data

id                                venue                 winner  \
121      335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
122      335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
123      335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
124      335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
125      335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
...         ...                                  ...                    ...   
193372  1237181  Dubai International Cricket Stadium         Mumbai Indians   
193373  1237181  Dubai International Cricket Stadium         Mumbai Indians   
193374  1237181  Dubai International Cricket Stadium         Mumbai Indians   
193375  1237181  Dubai International Cricket Stadium         Mumbai Indians   
193376  1237181  Dubai International Cricket Stadium         Mumbai Indians   

        Season toss_win_game_win  over  ball  Run_on_this_ball  is_wicket  \
121       2008                No     6     2                 0          0   
122       2008                No     6     3                 1          0   
123       2008                No     6     4                 1          0   
124       2008                No     6     5                 1          0   
125       2008                No     6     6                 0          0   
...        ...               ...   ...   ...               ...        ...   
193372    2020                No    17     6                 1          0   
193373    2020                No    18     1                 1          0   
193374    2020                No    18     2                 1          0   
193375    2020                No    18     3                 0          1   
193376    2020                No    18     4                 1          0   

                       batting_team           bowling_team  Target  \
121     Royal Challengers Bangalore  Kolkata Knight Riders     223   
122     Royal Challengers Bangalore  Kolkata Knight Riders     223   
123     Royal Challengers Bangalore  Kolkata Knight Riders     223   
124     Royal Challengers Bangalore  Kolkata Knight Riders     223   
125     Royal Challengers Bangalore  Kolkata Knight Riders     223   
...                             ...                    ...     ...   
193372               Mumbai Indians         Delhi Capitals     157   
193373               Mumbai Indians         Delhi Capitals     157   
193374               Mumbai Indians         Delhi Capitals     157   
193375               Mumbai Indians         Delhi Capitals     157   
193376               Mumbai Indians         Delhi Capitals     157   

        Ball_Number  
121              38  
122              39  
123              40  
124              41  
125              42  
...             ...  
193372          108  
193373          109  
193374          110  
193375          111  
193376          112  

[80314 rows x 13 columns]

In [126]:
data_temp=data[['id','Run_on_this_ball','is_wicket']]
data_temp

id  Run_on_this_ball  is_wicket
121      335982                 0          0
122      335982                 1          0
123      335982                 1          0
124      335982                 1          0
125      335982                 0          0
...         ...               ...        ...
193372  1237181                 1          0
193373  1237181                 1          0
193374  1237181                 1          0
193375  1237181                 0          1
193376  1237181                 1          0

[80314 rows x 3 columns]

In [127]:
data_temp.rename(columns={"Run_on_this_ball":"Runs"},inplace=True)
data_temp.rename(columns={"is_wicket":"Wickets"},inplace=True)
data_temp

id  Runs  Wickets
121      335982     0        0
122      335982     1        0
123      335982     1        0
124      335982     1        0
125      335982     0        0
...         ...   ...      ...
193372  1237181     1        0
193373  1237181     1        0
193374  1237181     1        0
193375  1237181     0        1
193376  1237181     1        0

[80314 rows x 3 columns]

In [128]:
data_temp=data_temp.groupby('id').cumsum()
data_temp

Runs  Wickets
121        0        0
122        1        0
123        2        0
124        3        0
125        3        0
...      ...      ...
193372   154        4
193373   155        4
193374   156        4
193375   156        5
193376   157        5

[80314 rows x 2 columns]

In [129]:
data=data.reset_index()
data

index       id                                venue  \
0         121   335982                M Chinnaswamy Stadium   
1         122   335982                M Chinnaswamy Stadium   
2         123   335982                M Chinnaswamy Stadium   
3         124   335982                M Chinnaswamy Stadium   
4         125   335982                M Chinnaswamy Stadium   
...       ...      ...                                  ...   
80309  193372  1237181  Dubai International Cricket Stadium   
80310  193373  1237181  Dubai International Cricket Stadium   
80311  193374  1237181  Dubai International Cricket Stadium   
80312  193375  1237181  Dubai International Cricket Stadium   
80313  193376  1237181  Dubai International Cricket Stadium   

                      winner  Season toss_win_game_win  over  ball  \
0      Kolkata Knight Riders    2008                No     6     2   
1      Kolkata Knight Riders    2008                No     6     3   
2      Kolkata Knight Riders    2008                No     6     4   
3      Kolkata Knight Riders    2008                No     6     5   
4      Kolkata Knight Riders    2008                No     6     6   
...                      ...     ...               ...   ...   ...   
80309         Mumbai Indians    2020                No    17     6   
80310         Mumbai Indians    2020                No    18     1   
80311         Mumbai Indians    2020                No    18     2   
80312         Mumbai Indians    2020                No    18     3   
80313         Mumbai Indians    2020                No    18     4   

       Run_on_this_ball  is_wicket                 batting_team  \
0                     0          0  Royal Challengers Bangalore   
1                     1          0  Royal Challengers Bangalore   
2                     1          0  Royal Challengers Bangalore   
3                     1          0  Royal Challengers Bangalore   
4                     0          0  Royal Challengers Bangalore   
...                 ...        ...                          ...   
80309                 1          0               Mumbai Indians   
80310                 1          0               Mumbai Indians   
80311                 1          0               Mumbai Indians   
80312                 0          1               Mumbai Indians   
80313                 1          0               Mumbai Indians   

                bowling_team  Target  Ball_Number  
0      Kolkata Knight Riders     223           38  
1      Kolkata Knight Riders     223           39  
2      Kolkata Knight Riders     223           40  
3      Kolkata Knight Riders     223           41  
4      Kolkata Knight Riders     223           42  
...                      ...     ...          ...  
80309         Delhi Capitals     157          108  
80310         Delhi Capitals     157          109  
80311         Delhi Capitals     157          110  
80312         Delhi Capitals     157          111  
80313         Delhi Capitals     157          112  

[80314 rows x 14 columns]

In [130]:
data_temp=data_temp.reset_index()
data_temp

index  Runs  Wickets
0         121     0        0
1         122     1        0
2         123     2        0
3         124     3        0
4         125     3        0
...       ...   ...      ...
80309  193372   154        4
80310  193373   155        4
80311  193374   156        4
80312  193375   156        5
80313  193376   157        5

[80314 rows x 3 columns]

In [131]:
data[['Runs','Wickets']]=data_temp[['Runs','Wickets']]
data

index       id                                venue  \
0         121   335982                M Chinnaswamy Stadium   
1         122   335982                M Chinnaswamy Stadium   
2         123   335982                M Chinnaswamy Stadium   
3         124   335982                M Chinnaswamy Stadium   
4         125   335982                M Chinnaswamy Stadium   
...       ...      ...                                  ...   
80309  193372  1237181  Dubai International Cricket Stadium   
80310  193373  1237181  Dubai International Cricket Stadium   
80311  193374  1237181  Dubai International Cricket Stadium   
80312  193375  1237181  Dubai International Cricket Stadium   
80313  193376  1237181  Dubai International Cricket Stadium   

                      winner  Season toss_win_game_win  over  ball  \
0      Kolkata Knight Riders    2008                No     6     2   
1      Kolkata Knight Riders    2008                No     6     3   
2      Kolkata Knight Riders    2008                No     6     4   
3      Kolkata Knight Riders    2008                No     6     5   
4      Kolkata Knight Riders    2008                No     6     6   
...                      ...     ...               ...   ...   ...   
80309         Mumbai Indians    2020                No    17     6   
80310         Mumbai Indians    2020                No    18     1   
80311         Mumbai Indians    2020                No    18     2   
80312         Mumbai Indians    2020                No    18     3   
80313         Mumbai Indians    2020                No    18     4   

       Run_on_this_ball  is_wicket                 batting_team  \
0                     0          0  Royal Challengers Bangalore   
1                     1          0  Royal Challengers Bangalore   
2                     1          0  Royal Challengers Bangalore   
3                     1          0  Royal Challengers Bangalore   
4                     0          0  Royal Challengers Bangalore   
...                 ...        ...                          ...   
80309                 1          0               Mumbai Indians   
80310                 1          0               Mumbai Indians   
80311                 1          0               Mumbai Indians   
80312                 0          1               Mumbai Indians   
80313                 1          0               Mumbai Indians   

                bowling_team  Target  Ball_Number  Runs  Wickets  
0      Kolkata Knight Riders     223           38     0        0  
1      Kolkata Knight Riders     223           39     1        0  
2      Kolkata Knight Riders     223           40     2        0  
3      Kolkata Knight Riders     223           41     3        0  
4      Kolkata Knight Riders     223           42     3        0  
...                      ...     ...          ...   ...      ...  
80309         Delhi Capitals     157          108   154        4  
80310         Delhi Capitals     157          109   155        4  
80311         Delhi Capitals     157          110   156        4  
80312         Delhi Capitals     157          111   156        5  
80313         Delhi Capitals     157          112   157        5  

[80314 rows x 16 columns]

In [132]:
data['Balls_Left']=120-data['Ball_Number']
data['Runs_Left']=data['Target']-data['Runs']
data

index       id                                venue  \
0         121   335982                M Chinnaswamy Stadium   
1         122   335982                M Chinnaswamy Stadium   
2         123   335982                M Chinnaswamy Stadium   
3         124   335982                M Chinnaswamy Stadium   
4         125   335982                M Chinnaswamy Stadium   
...       ...      ...                                  ...   
80309  193372  1237181  Dubai International Cricket Stadium   
80310  193373  1237181  Dubai International Cricket Stadium   
80311  193374  1237181  Dubai International Cricket Stadium   
80312  193375  1237181  Dubai International Cricket Stadium   
80313  193376  1237181  Dubai International Cricket Stadium   

                      winner  Season toss_win_game_win  over  ball  \
0      Kolkata Knight Riders    2008                No     6     2   
1      Kolkata Knight Riders    2008                No     6     3   
2      Kolkata Knight Riders    2008                No     6     4   
3      Kolkata Knight Riders    2008                No     6     5   
4      Kolkata Knight Riders    2008                No     6     6   
...                      ...     ...               ...   ...   ...   
80309         Mumbai Indians    2020                No    17     6   
80310         Mumbai Indians    2020                No    18     1   
80311         Mumbai Indians    2020                No    18     2   
80312         Mumbai Indians    2020                No    18     3   
80313         Mumbai Indians    2020                No    18     4   

       Run_on_this_ball  is_wicket                 batting_team  \
0                     0          0  Royal Challengers Bangalore   
1                     1          0  Royal Challengers Bangalore   
2                     1          0  Royal Challengers Bangalore   
3                     1          0  Royal Challengers Bangalore   
4                     0          0  Royal Challengers Bangalore   
...                 ...        ...                          ...   
80309                 1          0               Mumbai Indians   
80310                 1          0               Mumbai Indians   
80311                 1          0               Mumbai Indians   
80312                 0          1               Mumbai Indians   
80313                 1          0               Mumbai Indians   

                bowling_team  Target  Ball_Number  Runs  Wickets  Balls_Left  \
0      Kolkata Knight Riders     223           38     0        0          82   
1      Kolkata Knight Riders     223           39     1        0          81   
2      Kolkata Knight Riders     223           40     2        0          80   
3      Kolkata Knight Riders     223           41     3        0          79   
4      Kolkata Knight Riders     223           42     3        0          78   
...                      ...     ...          ...   ...      ...         ...   
80309         Delhi Capitals     157          108   154        4          12   
80310         Delhi Capitals     157          109   155        4          11   
80311         Delhi Capitals     157          110   156        4          10   
80312         Delhi Capitals     157          111   156        5           9   
80313         Delhi Capitals     157          112   157        5           8   

       Runs_Left  
0            223  
1            222  
2            221  
3            220  
4            220  
...          ...  
80309          3  
80310          2  
80311          1  
80312          1  
80313          0  

[80314 rows x 18 columns]

In [133]:
data['Wickets_Left']=10-data['Wickets']
data

index       id                                venue  \
0         121   335982                M Chinnaswamy Stadium   
1         122   335982                M Chinnaswamy Stadium   
2         123   335982                M Chinnaswamy Stadium   
3         124   335982                M Chinnaswamy Stadium   
4         125   335982                M Chinnaswamy Stadium   
...       ...      ...                                  ...   
80309  193372  1237181  Dubai International Cricket Stadium   
80310  193373  1237181  Dubai International Cricket Stadium   
80311  193374  1237181  Dubai International Cricket Stadium   
80312  193375  1237181  Dubai International Cricket Stadium   
80313  193376  1237181  Dubai International Cricket Stadium   

                      winner  Season toss_win_game_win  over  ball  \
0      Kolkata Knight Riders    2008                No     6     2   
1      Kolkata Knight Riders    2008                No     6     3   
2      Kolkata Knight Riders    2008                No     6     4   
3      Kolkata Knight Riders    2008                No     6     5   
4      Kolkata Knight Riders    2008                No     6     6   
...                      ...     ...               ...   ...   ...   
80309         Mumbai Indians    2020                No    17     6   
80310         Mumbai Indians    2020                No    18     1   
80311         Mumbai Indians    2020                No    18     2   
80312         Mumbai Indians    2020                No    18     3   
80313         Mumbai Indians    2020                No    18     4   

       Run_on_this_ball  is_wicket                 batting_team  \
0                     0          0  Royal Challengers Bangalore   
1                     1          0  Royal Challengers Bangalore   
2                     1          0  Royal Challengers Bangalore   
3                     1          0  Royal Challengers Bangalore   
4                     0          0  Royal Challengers Bangalore   
...                 ...        ...                          ...   
80309                 1          0               Mumbai Indians   
80310                 1          0               Mumbai Indians   
80311                 1          0               Mumbai Indians   
80312                 0          1               Mumbai Indians   
80313                 1          0               Mumbai Indians   

                bowling_team  Target  Ball_Number  Runs  Wickets  Balls_Left  \
0      Kolkata Knight Riders     223           38     0        0          82   
1      Kolkata Knight Riders     223           39     1        0          81   
2      Kolkata Knight Riders     223           40     2        0          80   
3      Kolkata Knight Riders     223           41     3        0          79   
4      Kolkata Knight Riders     223           42     3        0          78   
...                      ...     ...          ...   ...      ...         ...   
80309         Delhi Capitals     157          108   154        4          12   
80310         Delhi Capitals     157          109   155        4          11   
80311         Delhi Capitals     157          110   156        4          10   
80312         Delhi Capitals     157          111   156        5           9   
80313         Delhi Capitals     157          112   157        5           8   

       Runs_Left  Wickets_Left  
0            223            10  
1            222            10  
2            221            10  
3            220            10  
4            220            10  
...          ...           ...  
80309          3             6  
80310          2             6  
80311          1             6  
80312          1             5  
80313          0             5  

[80314 rows x 19 columns]

In [134]:
data.drop(['index'],axis='columns',inplace=True)

In [135]:
data.drop(['over','ball','Run_on_this_ball','is_wicket','Ball_Number','Wickets'],axis='columns',inplace=True)
data

id                                venue                 winner  \
0       335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
1       335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
2       335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
3       335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
4       335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
...        ...                                  ...                    ...   
80309  1237181  Dubai International Cricket Stadium         Mumbai Indians   
80310  1237181  Dubai International Cricket Stadium         Mumbai Indians   
80311  1237181  Dubai International Cricket Stadium         Mumbai Indians   
80312  1237181  Dubai International Cricket Stadium         Mumbai Indians   
80313  1237181  Dubai International Cricket Stadium         Mumbai Indians   

       Season toss_win_game_win                 batting_team  \
0        2008                No  Royal Challengers Bangalore   
1        2008                No  Royal Challengers Bangalore   
2        2008                No  Royal Challengers Bangalore   
3        2008                No  Royal Challengers Bangalore   
4        2008                No  Royal Challengers Bangalore   
...       ...               ...                          ...   
80309    2020                No               Mumbai Indians   
80310    2020                No               Mumbai Indians   
80311    2020                No               Mumbai Indians   
80312    2020                No               Mumbai Indians   
80313    2020                No               Mumbai Indians   

                bowling_team  Target  Runs  Balls_Left  Runs_Left  \
0      Kolkata Knight Riders     223     0          82        223   
1      Kolkata Knight Riders     223     1          81        222   
2      Kolkata Knight Riders     223     2          80        221   
3      Kolkata Knight Riders     223     3          79        220   
4      Kolkata Knight Riders     223     3          78        220   
...                      ...     ...   ...         ...        ...   
80309         Delhi Capitals     157   154          12          3   
80310         Delhi Capitals     157   155          11          2   
80311         Delhi Capitals     157   156          10          1   
80312         Delhi Capitals     157   156           9          1   
80313         Delhi Capitals     157   157           8          0   

       Wickets_Left  
0                10  
1                10  
2                10  
3                10  
4                10  
...             ...  
80309             6  
80310             6  
80311             6  
80312             5  
80313             5  

[80314 rows x 12 columns]

In [136]:
def result(row):
    return 1 if row['batting_team']==row['winner'] else 0
data['result']=data.apply(result,axis=1)
data

id                                venue                 winner  \
0       335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
1       335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
2       335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
3       335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
4       335982                M Chinnaswamy Stadium  Kolkata Knight Riders   
...        ...                                  ...                    ...   
80309  1237181  Dubai International Cricket Stadium         Mumbai Indians   
80310  1237181  Dubai International Cricket Stadium         Mumbai Indians   
80311  1237181  Dubai International Cricket Stadium         Mumbai Indians   
80312  1237181  Dubai International Cricket Stadium         Mumbai Indians   
80313  1237181  Dubai International Cricket Stadium         Mumbai Indians   

       Season toss_win_game_win                 batting_team  \
0        2008                No  Royal Challengers Bangalore   
1        2008                No  Royal Challengers Bangalore   
2        2008                No  Royal Challengers Bangalore   
3        2008                No  Royal Challengers Bangalore   
4        2008                No  Royal Challengers Bangalore   
...       ...               ...                          ...   
80309    2020                No               Mumbai Indians   
80310    2020                No               Mumbai Indians   
80311    2020                No               Mumbai Indians   
80312    2020                No               Mumbai Indians   
80313    2020                No               Mumbai Indians   

                bowling_team  Target  Runs  Balls_Left  Runs_Left  \
0      Kolkata Knight Riders     223     0          82        223   
1      Kolkata Knight Riders     223     1          81        222   
2      Kolkata Knight Riders     223     2          80        221   
3      Kolkata Knight Riders     223     3          79        220   
4      Kolkata Knight Riders     223     3          78        220   
...                      ...     ...   ...         ...        ...   
80309         Delhi Capitals     157   154          12          3   
80310         Delhi Capitals     157   155          11          2   
80311         Delhi Capitals     157   156          10          1   
80312         Delhi Capitals     157   156           9          1   
80313         Delhi Capitals     157   157           8          0   

       Wickets_Left  result  
0                10       0  
1                10       0  
2                10       0  
3                10       0  
4                10       0  
...             ...     ...  
80309             6       1  
80310             6       1  
80311             6       1  
80312             5       1  
80313             5       1  

[80314 rows x 13 columns]

In [137]:
data.drop(['winner'],axis='columns',inplace=True)

In [138]:
data.isnull().sum()

id                   0
venue                0
Season               0
toss_win_game_win    0
batting_team         0
bowling_team         0
Target               0
Runs                 0
Balls_Left           0
Runs_Left            0
Wickets_Left         0
result               0
dtype: int64

In [139]:
venues=data.venue.unique()
venues

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Maharashtra Cricket Association St

In [140]:
data.venue=data.venue.str.replace('M.Chinnaswamy Stadium','M Chinnaswamy Stadium')
data.venue=data.venue.str.replace('Punjab Cricket Association IS Bindra Stadium, Mohali','Punjab Cricket Association Stadium, Mohali')
data.venue=data.venue.str.replace('Maharashtra Cricket Association Stadium','Subrata Roy Sahara Stadium')

In [141]:
venues=data.venue.unique()
venues

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Holkar Cricket Stadium'], dtype=ob

In [142]:
len(venues)

30

In [143]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
LE=LabelEncoder()

In [144]:
data['venue']=LE.fit_transform(data['venue'])
data['batting_team']=le.fit_transform(data['batting_team'])
data['bowling_team']=le.fit_transform(data['bowling_team'])
data

id  venue  Season toss_win_game_win  batting_team  bowling_team  \
0       335982     13    2008                No             6             3   
1       335982     13    2008                No             6             3   
2       335982     13    2008                No             6             3   
3       335982     13    2008                No             6             3   
4       335982     13    2008                No             6             3   
...        ...    ...     ...               ...           ...           ...   
80309  1237181      6    2020                No             4             1   
80310  1237181      6    2020                No             4             1   
80311  1237181      6    2020                No             4             1   
80312  1237181      6    2020                No             4             1   
80313  1237181      6    2020                No             4             1   

       Target  Runs  Balls_Left  Runs_Left  Wickets_Left  result  
0         223     0          82        223            10       0  
1         223     1          81        222            10       0  
2         223     2          80        221            10       0  
3         223     3          79        220            10       0  
4         223     3          78        220            10       0  
...       ...   ...         ...        ...           ...     ...  
80309     157   154          12          3             6       1  
80310     157   155          11          2             6       1  
80311     157   156          10          1             6       1  
80312     157   156           9          1             5       1  
80313     157   157           8          0             5       1  

[80314 rows x 12 columns]

In [145]:
LE.classes_

array(['Barabati Stadium', 'Brabourne Stadium', 'Buffalo Park',
       'De Beers Diamond Oval', 'Dr DY Patil Sports Academy',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Dubai International Cricket Stadium', 'Eden Gardens',
       'Feroz Shah Kotla', 'Himachal Pradesh Cricket Association Stadium',
       'Holkar Cricket Stadium', 'JSCA International Stadium Complex',
       'Kingsmead', 'M Chinnaswamy Stadium',
       'MA Chidambaram Stadium, Chepauk', 'New Wanderers Stadium',
       'Newlands', 'OUTsurance Oval',
       'Punjab Cricket Association Stadium, Mohali',
       'Rajiv Gandhi International Stadium, Uppal',
       'Sardar Patel Stadium, Motera', 'Sawai Mansingh Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'Sharjah Cricket Stadium', 'Sheikh Zayed Stadium',
       "St George's Park", 'Subrata Roy Sahara Stadium',
       'SuperSport Park', 'Vidarbha Cricket Association Stadium, Jamtha',
       'Wankhede Stadium'], dtype=ob

In [146]:
le.classes_

array(['Chennai Super Kings', 'Delhi Capitals', 'Kings XI Punjab',
       'Kolkata Knight Riders', 'Mumbai Indians', 'Rajasthan Royals',
       'Royal Challengers Bangalore', 'Sunrisers Hyderabad'], dtype=object)

In [147]:
x=data.venue.unique()
x

array([13, 18,  8, 29,  7, 21, 19, 14,  4, 16, 25, 12, 27,  2, 15,  3, 17,
        1, 20,  0, 28,  9,  5, 26, 22, 11, 24, 23,  6, 10])

In [148]:
venues

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Holkar Cricket Stadium'], dtype=ob

In [149]:
venues1=pd.DataFrame(x,venues,columns=['code'])
venues1

code
M Chinnaswamy Stadium                                 13
Punjab Cricket Association Stadium, Mohali            18
Feroz Shah Kotla                                       8
Wankhede Stadium                                      29
Eden Gardens                                           7
Sawai Mansingh Stadium                                21
Rajiv Gandhi International Stadium, Uppal             19
MA Chidambaram Stadium, Chepauk                       14
Dr DY Patil Sports Academy                             4
Newlands                                              16
St George's Park                                      25
Kingsmead                                             12
SuperSport Park                                       27
Buffalo Park                                           2
New Wanderers Stadium                                 15
De Beers Diamond Oval                                  3
OUTsurance Oval                                       17
Brabourne Stadium                                      1
Sardar Patel Stadium, Motera                          20
Barabati Stadium                                       0
Vidarbha Cricket Association Stadium, Jamtha          28
Himachal Pradesh Cricket Association Stadium           9
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Sta...     5
Subrata Roy Sahara Stadium                            26
Shaheed Veer Narayan Singh International Stadium      22
JSCA International Stadium Complex                    11
Sheikh Zayed Stadium                                  24
Sharjah Cricket Stadium                               23
Dubai International Cricket Stadium                    6
Holkar Cricket Stadium                                10

In [150]:
y=data.batting_team.unique()
y

array([6, 2, 1, 3, 5, 4, 0, 7])

In [151]:
batting_code=pd.DataFrame(y,batting1,columns=['code'])
batting_code

code
Royal Challengers Bangalore     6
Kings XI Punjab                 2
Delhi Capitals                  1
Kolkata Knight Riders           3
Rajasthan Royals                5
Mumbai Indians                  4
Chennai Super Kings             0
Sunrisers Hyderabad             7

In [152]:
z=data.bowling_team.unique()
z

array([3, 0, 5, 4, 7, 2, 6, 1])

In [153]:
bowling_code=pd.DataFrame(z,bowling1,columns=['code'])
bowling_code


code
Kolkata Knight Riders           3
Chennai Super Kings             0
Rajasthan Royals                5
Mumbai Indians                  4
Sunrisers Hyderabad             7
Kings XI Punjab                 2
Royal Challengers Bangalore     6
Delhi Capitals                  1

In [154]:
X=data[['batting_team','bowling_team','venue','Runs_Left','Balls_Left','Wickets_Left']]

In [155]:
y=data['result']

In [156]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.7,random_state=10)

In [157]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100)

In [158]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [159]:
X_test1,X_test2,y_test1,y_test2=train_test_split(X_test,y_test,test_size=0.5,random_state=100)

In [160]:
model.score(X_test1,y_test1)

0.9643543223052294

In [161]:
model.score(X_test2,y_test2)

0.9639985770188545

In [162]:
model.score(X_test1,y_test1)

0.9643543223052294